// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// findSIMQ
extern "C" SEXP findSIMQ(SEXP SIM, SEXP X, SEXP Xbin, SEXP probs, SEXP confLevel, SEXP approx);
RcppExport SEXP _nlmeVPC_findSIMQ(SEXP SIMSEXP, SEXP XSEXP, SEXP XbinSEXP, SEXP probsSEXP, SEXP confLevelSEXP, SEXP approxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type SIM(SIMSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xbin(XbinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type confLevel(confLevelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type approx(approxSEXP);
    rcpp_result_gen = Rcpp::wrap(findSIMQ(SIM, X, Xbin, probs, confLevel, approx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nlmeVPC_findSIMQ", (DL_FUNC) &_nlmeVPC_findSIMQ, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_nlmeVPC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
